"use client";

import { motion } from "framer-motion";
import { Card } from "@/components/ui/Card";

export function Stats() {
  const stats = [
    { value: "₹2.4 Cr+", label: "Revenue Generated by Users" },
    { value: "85,000+", label: "Hours Saved Across All Users" },
    { value: "340+", label: "Automation Workflows Deployed" },
    { value: "10,000+", label: "Creators Using Our Templates" },
  ];

  return (
    <section className="py-24 bg-white">
      <div className="container max-w-7xl mx-auto px-6">
        <h2 className="text-center text-xl font-bold text-brand-black mb-12 tracking-tight uppercase">
          Trusted By 10,000+ Digital Creators Worldwide
        </h2>
        
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
          {stats.map((stat, idx) => (
            <motion.div
              key={idx}
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ delay: idx * 0.1 }}
            >
              <Card className="text-center py-10" hover={false}>
                <div className="text-3xl font-extrabold text-brand-black mb-2 tracking-tighter">
                  {stat.value}
                </div>
                <div className="text-sm font-medium text-brand-gray tracking-tight">
                  {stat.label}
                </div>
              </Card>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
